name: My Website [CI/CD]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Unit Tests
        run: yarn test
      - name: Run Build
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist-artifact
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git User
        run: |
          git config --local user.email "email.gabriel.lima@gmail.com"
          git config --local user.name "Gabriel Lima"
      - name: Download build Artifact
        uses: actions/download-artifact@v1
        with:
          name: dist-artifact
      - name: Deploy to gh-pages
        run: yarn deploy
        if: github.ref == 'refs/heads/master'
