name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test
      
      - name: Run Build
        run: yarn build
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist-artifact
          path: dist
