name: My Website [CI/CD]
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  poll: production
  mainBranch: 'refs/heads/master'

jobs:
  build:
    runs-on: ${{ env.poll }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Unit Tests
        run: yarn test
      - name: Run Build
        run: yarn build
  deploy:
    needs: build
    runs-on: ${{ env.poll }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Git User
        run: |
          git config --local user.email "email.gabriel.lima@gmail.com"
          git config --local user.name "Gabriel Lima"
      - name: Deploy to gh-pages
        run: yarn deploy
        if: github.ref == ${{ env.mainBranch }}
