name: My Website [CI/CD]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the datetime
        id: get_datetime
        uses: ajilraju/actions-date@v0.0.2
          with:
            args: date +%y.%m.%d
      - name: Print the datetime
        run: |
          echo ${{ steps.get_datetime.outputs.datetime_str }}
        shell: bash
      # - name: Install Dependencies
      #   run: yarn install --frozen-lockfile
      # - name: Run Unit Tests
      #   run: yarn test
      # - name: Run Build
      #   run: yarn build
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: dist-artifact
      #     path: dist
          
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: gh-pages
  #     - name: Get the datetime
  #       id: get_datetime
  #       uses: ajilraju/actions-date@v0.0.2
  #         with:
  #           args: date +%y.%m.%d
  #     - name: Print the datetime
  #       run: |
  #         echo ${{ steps.get_datetime.outputs.datetime_str }}
  #       shell: bash
      # - name: Download build Artifact
      #   uses: actions/download-artifact@v1
      #     with:
      #       name: dist-artifact
      #       path: .
      # - name: Set Git User
      #   run: |
      #     git config --local user.email "email.gabriel.lima@gmail.com"
      #     git config --local user.name "Gabriel Lima"
      #   id: get_datetime
      #   uses: ccccmagicboy/get_datetime@master
      
      # - name: Git Commit/Push
      #   run: |
      #     git add .
      #     git commit -m 'Release ${{ steps.with.args }}:${{ github.run_number }}'
      #     git push -f
