name: Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    name: GH-Pages
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: rm -rf ./*

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

      