name: CI CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install Dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Run Unit Tests
  #       run: yarn test
      
  #     - name: Run Build
  #       run: yarn build
      
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: dist-artifact
  #         path: dist

  # release:
  #   name: Release
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - name: Install Dependencies
  #       run: yarn install --frozen-lockfile
  #     - name: Update release version and changelog
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: npm run release:local

  deploy:
    name: Deploy to GH-Pages
    # needs: release
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
        
      # - name: Download build Artifact
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: dist-artifact
      #     path: .

      - name: Set Git User
        run: |
          git config --local user.email "email.gabriel.lima@gmail.com"
          git config --local user.name "Gabriel Lima"
      
      - name: Git Commit and Push
        run: |
          # git add .
          # git push -f
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo 'chore(release): ${PACKAGE_VERSION}'
        shell: bash 
      