name: My Website [CI/CD]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test
      
      - name: Run Build
        run: yarn build
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist-artifact
          path: dist
          
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download build Artifact
        uses: actions/download-artifact@v1
        with:
          name: dist-artifact
          path: .

      - name: Set date var
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set Git User
        run: |
          git config --local user.email "email.gabriel.lima@gmail.com"
          git config --local user.name "Gabriel Lima"
      
      - name: Git Commit/Push
        run: |
          git add .
          git commit -m 'Release ${{ steps.date.outputs.date }}:${{ github.run_number }}'
          git push -f
        shell: bash 

